name: Build and release

on: push
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    # SBCL on Windows does not support CRLF.
    - name: Ensure LF line endings
      run: git config --global core.autocrlf input
      
    - name: Check out sbcl-builds
      uses: actions/checkout@v4
      with:
        path: sbcl-builds

    - name: Check out SBCL mirror
      uses: actions/checkout@v4
      with:
        repository: sbcl/sbcl
        path: sbcl-source
        # Make sure we don't do a shallow clone.
        # We need the full commit history, as this is required by 'git describe',
        # which is called by generate-version.sh.
        fetch-depth: 0
        
    - name: Set environment variables
      run: |
           $SBCL_HASH = Set-Location -Path .\sbcl-source; git rev-parse --short HEAD
           Write-Output ("SBCL_HASH=" + $SBCL_HASH) | Out-File -FilePath $env:GITHUB_ENV -Append
           Write-Output ("SBCL_HOME=" + $env:GITHUB_WORKSPACE + "\sbcl-builds") | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          make
          git
          zip
          unzip
          mingw-w64-ucrt-x86_64-gcc
          
    - name: Build SBCL
      shell: msys2 {0}
      run: |
           echo CURRENT DIR: $(pwd), WORKSPACE DIR: $GITHUB_WORKSPACE
           cd sbcl-builds 
           unzip sbcl-2.3.2.zip
           cd ../sbcl-source
           sh make.sh --prefix=../build --xc-host=$SBCL_HOME/sbcl.exe
           unset SBCL_HOME
           sh install.sh   
           cd "$GITHUB_WORKSPACE"
           zip -r sbcl-ucrt64-$SBCL_HASH.zip build
           
#    - name: Release
#      uses: softprops/action-gh-release@v1
#      with:
#        files: 
    

# TELL USER IN README TO SET SBCL_HOME!
