name: Build and Release

on: push
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    # SBCL on Windows does not support CRLF.
    - name: Ensure LF line endings
      run: git config --global core.autocrlf input
      
    - name: Check out sbcl-builds
      uses: actions/checkout@v4
      with:
        path: sbcl-builds

    - name: Check out SBCL mirror
      uses: actions/checkout@v4
      with:
        repository: sbcl/sbcl
        path: sbcl-source

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          zip
          unzip
          curl
          mingw-w64-ucrt-x86_64-gcc
          
    - name: Build SBCL
      shell: msys2 {0}
      run: |
           cd sbcl-builds 
           unzip sbcl-2.3.2.zip
           cd ../sbcl-source
           SBCL_HOME=../sbcl-builds sh make.sh --prefix=../build --xc-host=$SBCL_HOME/sbcl.exe
           unset SBCL_HOME
           sh install.sh   
           cd "$GITHUB_WORKSPACE"
           zip -r sbcl-ucrt64-$(cd sbcl-source && git rev-parse --short HEAD).zip build

# Focus on getting the build working for now
#  release:
#    name: Release
#    needs: build

# TELL USER IN README TO SET SBCL_HOME!
